apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: zhiyong-tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: zhiyong-tanzu-java-web-app
spec:
  params:
    - name: run-image
      value: https://hub.docker.com/repository/docker/showpune/tanzu-test/zhiyong-tanzu-java-web-app
  source:
    git:
      url: https://github.com/sample-accelerators/zhiyong-tanzu-java-web-app
      ref:
        branch: main
